### ISSUE TITLE
Finalize first version

### ISSUE THREAD

**Issue by blizzz** [nextcloud/changelog_server#1]
* [x] integration tests (check headers!, contents) #4 
* [x] schema for whats-new xml #3 
* [x] get this into transifex somehow (well, as soon as there is anything to translate…) #2 

otherwise the logic is already pushed to master. It's not that much after all, and the scaffolding taken from the updater server.

fyi @MorrisJobke @rullzer 

P.S.: showing off cases invalid/unavailable info, info, and cached (with test data)

![screenshot_20180611_230123](https://user-images.githubusercontent.com/2184312/41256915-5e1734ec-6dcb-11e8-8457-4676664b880a.png)

**Comment by blizzz** [comment]
@MorrisJobke could you also turn on travis for this repo? i don't have sufficient permissions 😮

**Comment by rullzer** [comment]
@blizzz travis or drone?

**Comment by blizzz** [comment]
Don't really care. I copypastad the travis conf ;)

**Comment by rullzer** [comment]
enabled

**Comment by blizzz** [comment]
all done :tada:
